import { StyleSheet } from 'react-native';
import appStyle from '../../appStyle';

/**
 * Styles for CustomWorkoutPage component
 * Extracted for better code organization and maintainability
 */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appStyle.colors.background,
  },
  headerContainer: {
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    overflow: 'hidden',
    ...appStyle.shadows.large,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 28,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 5,
  },
  subtitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
    fontWeight: '400',
  },
  scrollView: {
    flex: 1,
    backgroundColor: appStyle.colors.background,
  },
  scrollViewContent: {
    paddingBottom: 0,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: appStyle.colors.cardBackground,
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 10,
    gap: 10,
    minHeight: 52,
  },
  tabButtonActive: {
    backgroundColor: appStyle.colors.accent,
  },
  tabText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    fontWeight: '500',
  },
  tabTextActive: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
    fontWeight: '700',
  },
  viewToggle: {
    flexDirection: 'row',
    backgroundColor: appStyle.colors.surface,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
    borderRadius: 12,
    padding: 4,
  },
  toggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    gap: 8,
  },
  toggleButtonActive: {
    backgroundColor: appStyle.colors.primary,
  },
  toggleButtonText: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  header: {
    paddingTop: 60,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  title: {
    color: appStyle.colors.text,
    fontSize: 28,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 5,
  },
  subtitle: {
    color: appStyle.colors.accent,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  form: {
    padding: 20,
    paddingBottom: 0,
  },
  inputCard: {
    flexDirection: 'row',
    backgroundColor: appStyle.colors.surface,
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  inputContent: {
    flex: 1,
    marginLeft: 15,
  },
  inputLabel: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 5,
  },
  inputValue: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  textInput: {
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
    paddingVertical: 5,
    includeFontPadding: false,
  },
  notesInput: {
    minHeight: 80,
    maxHeight: 120,
    marginTop: 5,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    color: appStyle.colors.text,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  exerciseCount: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  exercisesList: {
    marginBottom: 15,
  },
  exerciseCard: {
    flexDirection: 'row',
    backgroundColor: appStyle.colors.surface,
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 4,
  },
  exerciseDetails: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  setsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  setDetail: {
    color: '#888',
    fontSize: 13,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  // Sets modal styles
  setsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  addSetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appStyle.colors.primary + '20',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  addSetButtonText: {
    color: appStyle.colors.primary,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  setRow: {
    flexDirection: 'row',
    backgroundColor: '#363636',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
    gap: 10,
  },
  setNumber: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: appStyle.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setNumberText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  setInputs: {
    flex: 1,
    flexDirection: 'row',
    gap: 15,
  },
  setInputGroup: {
    flex: 1,
  },
  setInputLabel: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 5,
  },
  setInputWithButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
  },
  setTextInput: {
    flex: 1,
    padding: 10,
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  weightButton: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setActions: {
    flexDirection: 'row',
    gap: 8,
  },
  setActionButton: {
    padding: 6,
  },
  deleteExerciseButton: {
    padding: 8,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  emptyExercises: {
    backgroundColor: appStyle.colors.surface,
    padding: 40,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 15,
  },
  emptyExercisesText: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginTop: 15,
    marginBottom: 5,
  },
  emptyExercisesSubtext: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  addExerciseButton: {
    borderRadius: 16,
    overflow: 'hidden',
    minHeight: 56,
    shadowColor: '#FF3333',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addExerciseButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    minHeight: 56,
  },
  addExerciseButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginLeft: 8,
    fontWeight: '700',
  },
  saveButtonGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 30,
    paddingHorizontal: 0,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#FF6B35',
    paddingVertical: 16,
    borderRadius: 16,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
  },
  cancelButtonText: {
    color: '#FFD700',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    fontWeight: '600',
  },
  saveButton: {
    flex: 2,
    borderRadius: 16,
    marginLeft: 10,
    overflow: 'hidden',
    minHeight: 56,
    shadowColor: '#FF3333',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    fontWeight: '700',
  },
  dismissArea: {
    height: 100,
  },
  // List View Styles
  listContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 0,
  },
  workoutsList: {
    gap: 15,
  },
  workoutCard: {
    backgroundColor: appStyle.colors.surface,
    borderRadius: 12,
    padding: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    position: 'relative',
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    position: 'relative',
  },
  workoutHeaderLeft: {
    flex: 1,
    gap: 10,
  },
  workoutTypesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 5,
  },
  workoutTypeBadge: {
    backgroundColor: appStyle.colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  workoutTypeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  selectedTypesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 5,
  },
  selectedTypeChip: {
    backgroundColor: appStyle.colors.primary + '30',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appStyle.colors.primary,
  },
  selectedTypeChipText: {
    color: appStyle.colors.primary,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutDay: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  deleteWorkoutButton: {
    padding: 8,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 10,
  },
  workoutExercises: {
    marginBottom: 10,
  },
  workoutExercisesTitle: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 8,
  },
  workoutExerciseItem: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 4,
  },
  workoutExerciseMore: {
    color: 'rgba(255, 255, 255, 0.4)',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    fontStyle: 'italic',
    marginTop: 4,
  },
  workoutNotes: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#363636',
  },
  workoutNotesLabel: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 4,
  },
  workoutNotesText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyTitle: {
    color: appStyle.colors.text,
    fontSize: 20,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginTop: 20,
    marginBottom: 10,
  },
  emptySubtitle: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 30,
  },
  createButton: {
    backgroundColor: appStyle.colors.primary,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 12,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: appStyle.colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    padding: 20,
    flexGrow: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    color: appStyle.colors.text,
    fontSize: 20,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  modalSection: {
    marginBottom: 20,
  },
  modalLabel: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 10,
  },
  modalSubLabel: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginTop: 10,
    marginBottom: 10,
  },
  modalTextInput: {
    backgroundColor: '#363636',
    borderRadius: 8,
    padding: 12,
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  dayOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    backgroundColor: '#363636',
  },
  dayOptionSelected: {
    backgroundColor: appStyle.colors.primary + '30',
    borderWidth: 1,
    borderColor: appStyle.colors.primary,
  },
  dayOptionText: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  dayOptionTextSelected: {
    color: appStyle.colors.primary,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutTypeOption: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#363636',
    margin: 5,
    minWidth: '45%',
  },
  workoutTypeOptionSelected: {
    backgroundColor: appStyle.colors.primary + '30',
    borderWidth: 1,
    borderColor: appStyle.colors.primary,
  },
  workoutTypeOptionText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  workoutTypeOptionTextSelected: {
    color: appStyle.colors.primary,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  exerciseOption: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#363636',
    margin: 5,
    alignItems: 'center',
  },
  exerciseOptionSelected: {
    backgroundColor: appStyle.colors.primary + '30',
    borderWidth: 1,
    borderColor: appStyle.colors.primary,
  },
  exerciseOptionText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  exerciseOptionTextSelected: {
    color: appStyle.colors.primary,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  saveExercisePrompt: {
    backgroundColor: '#363636',
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
  },
  saveExercisePromptText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 10,
  },
  saveExercisePromptButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  saveExercisePromptButton: {
    flex: 1,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#2C2C2C',
    alignItems: 'center',
  },
  saveExercisePromptButtonPrimary: {
    backgroundColor: appStyle.colors.primary,
  },
  saveExercisePromptButtonText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  saveExercisePromptButtonTextPrimary: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 20,
  },
  modalDoneButton: {
    flex: 1,
    backgroundColor: appStyle.colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalDoneButtonText: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: appStyle.colors.accent,
    paddingVertical: 15,
    borderRadius: 12,
    marginRight: 10,
    alignItems: 'center',
  },
  modalCancelButtonText: {
    color: appStyle.colors.accent,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  modalSaveButton: {
    flex: 2,
    backgroundColor: appStyle.colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    marginLeft: 10,
    alignItems: 'center',
  },
  modalSaveButtonText: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  // Edit Modal Styles
  editModalContainer: {
    flex: 1,
    backgroundColor: appStyle.colors.background,
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 50,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  editModalTitle: {
    color: appStyle.colors.text,
    fontSize: 24,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  editModalCloseButton: {
    padding: 5,
  },
  editModalContent: {
    flex: 1,
    padding: 20,
  },
  editSection: {
    marginBottom: 25,
  },
  editExerciseCard: {
    backgroundColor: appStyle.colors.surface,
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#363636',
  },
  editExerciseName: {
    color: appStyle.colors.text,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 12,
  },
  setsListContainer: {
    marginBottom: 10,
  },
  editSetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#363636',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    gap: 10,
  },
  setNumberSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: appStyle.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setNumberSmallText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  editSetInputs: {
    flex: 1,
    flexDirection: 'row',
    gap: 12,
  },
  editSetInputGroup: {
    flex: 1,
  },
  editSetLabel: {
    color: '#888',
    fontSize: 11,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 5,
  },
  editSetInputWithButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
  },
  editSetTextInput: {
    flex: 1,
    padding: 8,
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  editSetTextInputSingle: {
    padding: 8,
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  weightButtonSmall: {
    padding: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeSetButton: {
    padding: 6,
  },
  addSetToExerciseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: appStyle.colors.primary + '20',
    padding: 10,
    borderRadius: 8,
    gap: 6,
    marginTop: 5,
  },
  addSetToExerciseText: {
    color: appStyle.colors.primary,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  saveEditedWorkoutButton: {
    backgroundColor: appStyle.colors.primary,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  saveEditedWorkoutButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  editWorkoutSummary: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: appStyle.colors.surface,
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
  },
  editWorkoutSummaryItem: {
    alignItems: 'center',
  },
  editWorkoutSummaryLabel: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 4,
  },
  editWorkoutSummaryValue: {
    color: appStyle.colors.text,
    fontSize: 20,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  // Workout Logging Styles
  workoutLogHeader: {
    backgroundColor: appStyle.colors.surface,
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#363636',
  },
  workoutLogHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  workoutLogTitle: {
    color: appStyle.colors.text,
    fontSize: 24,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 4,
  },
  workoutLogSubtitle: {
    color: appStyle.colors.accent,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  workoutTimerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appStyle.colors.primary + '20',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
  },
  workoutTimerText: {
    color: appStyle.colors.primary,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  restTimerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#363636',
    padding: 12,
    borderRadius: 10,
    gap: 8,
  },
  restTimerCardActive: {
    backgroundColor: appStyle.colors.primary + '30',
    borderWidth: 1,
    borderColor: appStyle.colors.primary,
  },
  restTimerText: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  restTimerTextActive: {
    color: '#FFD700',
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutLogContent: {
    flex: 1,
    padding: 20,
  },
  workoutLogSection: {
    marginBottom: 25,
  },
  workoutLogSectionTitle: {
    color: appStyle.colors.text,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 15,
  },
  workoutLogExerciseCard: {
    backgroundColor: appStyle.colors.surface,
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
  },
  workoutLogExerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  workoutLogExerciseName: {
    color: appStyle.colors.text,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
    flex: 1,
  },
  prBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFD700' + '30',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  prBadgeText: {
    color: '#FFD700',
    fontSize: 12,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutLogSetsContainer: {
    marginBottom: 10,
  },
  workoutLogSetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#363636',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    gap: 10,
  },
  workoutLogSetRowPR: {
    backgroundColor: '#FFD700' + '20',
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  workoutLogSetNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: appStyle.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  workoutLogSetNumberText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutLogSetInputs: {
    flex: 1,
    flexDirection: 'row',
    gap: 12,
  },
  workoutLogSetInputGroup: {
    flex: 1,
  },
  workoutLogSetLabel: {
    color: '#888',
    fontSize: 11,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 5,
  },
  workoutLogSetInputWithButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
  },
  workoutLogSetTextInput: {
    flex: 1,
    padding: 10,
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  workoutLogSetTextInputSingle: {
    padding: 10,
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  workoutLogWeightButton: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  workoutLogRemoveSetButton: {
    padding: 6,
  },
  workoutLogAddSetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: appStyle.colors.primary + '20',
    padding: 10,
    borderRadius: 8,
    gap: 6,
    marginTop: 5,
  },
  workoutLogAddSetText: {
    color: appStyle.colors.primary,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutLogExerciseVolume: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginTop: 8,
    textAlign: 'right',
  },
  workoutLogNotesInput: {
    backgroundColor: '#363636',
    borderRadius: 8,
    padding: 12,
    minHeight: 80,
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  workoutLogSummary: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: appStyle.colors.surface,
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
  },
  workoutLogSummaryItem: {
    alignItems: 'center',
  },
  workoutLogSummaryLabel: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 4,
  },
  workoutLogSummaryValue: {
    color: appStyle.colors.text,
    fontSize: 20,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutLogActions: {
    flexDirection: 'row',
    padding: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#363636',
    gap: 10,
  },
  workoutLogCancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: appStyle.colors.accent,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  workoutLogCancelButtonText: {
    color: appStyle.colors.accent,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  workoutLogFinishButton: {
    flex: 2,
    backgroundColor: appStyle.colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  workoutLogFinishButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  startWorkoutButton: {
    padding: 8,
  },
  // Rest Timer Modal Styles
  restTimerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  restTimerModalContent: {
    backgroundColor: appStyle.colors.surface,
    borderRadius: 20,
    padding: 30,
    width: '85%',
    alignItems: 'center',
  },
  restTimerModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 30,
  },
  restTimerModalTitle: {
    color: appStyle.colors.text,
    fontSize: 24,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  restTimerDisplay: {
    alignItems: 'center',
    marginBottom: 30,
  },
  restTimerDisplayText: {
    color: appStyle.colors.primary,
    fontSize: 48,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 10,
  },
  restTimerDisplayLabel: {
    color: '#888',
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  restTimerPresets: {
    width: '100%',
    marginBottom: 20,
  },
  restTimerPresetsLabel: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 15,
  },
  restTimerPresetsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  restTimerPresetButton: {
    backgroundColor: '#363636',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: '30%',
    alignItems: 'center',
  },
  restTimerPresetText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  restTimerControls: {
    width: '100%',
  },
  restTimerStartButton: {
    flexDirection: 'row',
    backgroundColor: appStyle.colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  restTimerStartButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  restTimerStopButton: {
    flexDirection: 'row',
    backgroundColor: '#F44336',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  restTimerStopButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  // Muscle Group Tabs
  muscleGroupTabs: {
    marginVertical: 15,
    maxHeight: 50,
  },
  muscleGroupTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#363636',
    marginRight: 8,
  },
  muscleGroupTabActive: {
    backgroundColor: appStyle.colors.primary,
  },
  muscleGroupTabText: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  muscleGroupTabTextActive: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  // Search Styles
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#363636',
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 15,
    marginTop: 10,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  searchClearButton: {
    padding: 4,
  },
  exercisesListContainer: {
    maxHeight: 400,
    marginTop: 10,
  },
  exercisesListFlatList: {
    flex: 1,
    marginTop: 10,
  },
  exercisesListContent: {
    paddingBottom: 20,
  },
  customExercisePrompt: {
    backgroundColor: appStyle.colors.primary + '20',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: appStyle.colors.primary,
  },
  customExercisePromptText: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 10,
  },
  customExerciseCreateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: appStyle.colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    gap: 6,
  },
  customExerciseCreateButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  emptySearchResults: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptySearchText: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginTop: 15,
    marginBottom: 5,
  },
  emptySearchSubtext: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  saveExercisePromptSubtext: {
    color: '#888',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 15,
    marginTop: 5,
  },
});

export default styles;
