import { StyleSheet, Dimensions } from 'react-native';
import appStyle from '../../appStyle';

/**
 * Styles for StatsPage component
 * Extracted for better code organization and maintainability
 */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appStyle.colors.background,
  },
  headerContainer: {
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    overflow: 'hidden',
    ...appStyle.shadows.large,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 28,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 5,
  },
  subtitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  timeRangeContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  timeRangeButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: appStyle.colors.surface,
    marginHorizontal: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
    minHeight: 40,
  },
  timeRangeButtonActive: {
    borderColor: '#FF6B35',
    overflow: 'hidden',
  },
  timeRangeButtonGradient: {
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    width: '100%',
  },
  timeRangeText: {
    color: appStyle.colors.textSecondary,
    fontSize: 13,
    fontFamily: appStyle.fonts.regular.fontFamily,
    fontWeight: '500',
  },
  timeRangeTextActive: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: appStyle.colors.cardBackground,
    padding: 15,
    borderRadius: 16,
    width: '48%',
    marginBottom: 10,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
    ...appStyle.shadows.small,
  },
  statValue: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginVertical: 4,
  },
  statLabel: {
    color: '#888',
    fontSize: 10,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: appStyle.colors.cardBackground,
    borderRadius: 16,
    padding: 4,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
  },
  tabButton: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    minHeight: 44,
  },
  tabButtonActive: {
    overflow: 'hidden',
  },
  tabButtonGradient: {
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  tabButtonInactive: {
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  tabText: {
    color: appStyle.colors.text,
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
    includeFontPadding: false,
  },
  tabTextActive: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
    textAlign: 'center',
    includeFontPadding: false,
  },
  subTabContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: appStyle.colors.cardBackground,
    borderRadius: 16,
    padding: 4,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
  },
  subTabButton: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    minHeight: 40,
  },
  subTabButtonActive: {
    overflow: 'hidden',
  },
  subTabButtonGradient: {
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  subTabButtonInactive: {
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  subTabText: {
    color: appStyle.colors.text,
    fontSize: 11,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
    includeFontPadding: false,
  },
  subTabTextActive: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
    textAlign: 'center',
    includeFontPadding: false,
  },
  chartContainer: {
    backgroundColor: appStyle.colors.cardBackground,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
    ...appStyle.shadows.medium,
  },
  chartTitle: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 5,
    alignSelf: 'flex-start',
  },
  chartSubtitle: {
    color: appStyle.colors.textSecondary,
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  chart: {
    borderRadius: 12,
  },
  emptyChart: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyChartText: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginTop: 10,
  },
  emptyChartSubtext: {
    color: '#666',
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginTop: 5,
    textAlign: 'center',
  },
  insightsContainer: {
    backgroundColor: appStyle.colors.cardBackground,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
    ...appStyle.shadows.small,
  },
  insightsTitle: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 10,
  },
  insightItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  insightText: {
    color: appStyle.colors.text,
    fontSize: 12,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginLeft: 8,
    flex: 1,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  summaryLabel: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  summaryValue: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  // Exercise Stats Styles
  exerciseListContainer: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    color: appStyle.colors.text,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 15,
  },
  exerciseCard: {
    backgroundColor: appStyle.colors.cardBackground,
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
    ...appStyle.shadows.small,
  },
  exerciseCardSelected: {
    borderColor: appStyle.colors.accent,
    backgroundColor: appStyle.colors.surfaceElevated,
  },
  exerciseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  exerciseCardName: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    flex: 1,
  },
  prBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  prBadgeText: {
    color: '#FFD700',
    fontSize: 10,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  exerciseCardStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exerciseStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  exerciseStatLabel: {
    color: appStyle.colors.textSecondary,
    fontSize: 10,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 4,
  },
  exerciseStatValue: {
    color: appStyle.colors.text,
    fontSize: 14,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  emptyStateText: {
    color: appStyle.colors.text,
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginTop: 15,
    marginBottom: 8,
  },
  emptyStateSubtext: {
    color: '#888',
    fontSize: 14,
    fontFamily: appStyle.fonts.regular.fontFamily,
    textAlign: 'center',
  },
  exerciseChartsContainer: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  selectedExerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  selectedExerciseTitle: {
    color: appStyle.colors.text,
    fontSize: 20,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  exerciseChartTabs: {
    flexDirection: 'row',
    backgroundColor: appStyle.colors.cardBackground,
    borderRadius: 16,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
  },
  exerciseChartTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 8,
  },
  exerciseChartTabActive: {
    backgroundColor: appStyle.colors.accent,
  },
  exerciseChartTabText: {
    color: appStyle.colors.text,
    fontSize: 11,
    fontFamily: appStyle.fonts.regular.fontFamily,
  },
  exerciseChartTabTextActive: {
    color: '#FFFFFF',
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
  prContainer: {
    backgroundColor: appStyle.colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
    ...appStyle.shadows.small,
  },
  prTitle: {
    color: appStyle.colors.text,
    fontSize: 16,
    fontFamily: appStyle.fonts.bold.fontFamily,
    marginBottom: 15,
  },
  prGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  prItem: {
    width: '48%',
    backgroundColor: appStyle.colors.surfaceElevated,
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appStyle.colors.cardBorder,
  },
  prLabel: {
    color: appStyle.colors.textSecondary,
    fontSize: 10,
    fontFamily: appStyle.fonts.regular.fontFamily,
    marginBottom: 6,
  },
  prValue: {
    color: '#FFD700',
    fontSize: 18,
    fontFamily: appStyle.fonts.bold.fontFamily,
  },
});

export default styles;
